# Generated by Django 3.2.5 on 2022-06-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('guid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('eye_color', models.CharField(max_length=20)),
                ('has_died', models.BooleanField()),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_loader.company')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable_name', models.CharField(max_length=20)),
                ('person', models.ManyToManyField(to='data_loader.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonFriend', to='data_loader.person')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Person', to='data_loader.person')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=20)),
                ('person', models.ManyToManyField(to='data_loader.Person')),
            ],
        ),
    ]
