# Generated by Django 3.2.5 on 2022-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='data_loader.Person'),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='data_loader.Person'),
        ),
    ]
